### ISSUE TITLE
Move continuous integration from Travis CI to another platform

### ISSUE THREAD

**Issue by vc1492a** [vc1492a/PyNomaly#51]
Travis CI is no longer free. PyNomaly should be migrated to an alternative continuous integration platform such as Tox or Circle CI.

**Comment by IroNEDR** [comment]
I will take care of this.

**Comment by IroNEDR** [comment]
Do I understand it correctly, that the current travis ci pipeline only runs the tests and returns the results? Since this is an open source project, it would make sense to move to github actions.
Furthermore, we should consider directly setting up the actions to automatically push to the pypi repository on successful builds.  
If you agree @vc1492a, give me thumbs up and I will start setting this up.

**Comment by vc1492a** [comment]
@IroNEDR  sounds great with me. 

Yes, your understanding is correct - we leveraged Travis CI in the past to run our unit tests against a set of Python versions (e.g. Python 3.6-3.12) and make sure the tests pass on each platform. 

Also agree we should consider further automation to push directly to PyPI on successful build and tagging and releasing to the main branch - we might want to consider some other safeguards for the main branch before implementing such an automation, however.
